import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Category",
  description: "Generated by create next app",
};

export default function layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div>
      <p>Main category layout</p> {children}
    </div>
  );
}
